# Site settings
title: Blog - BoolFunc
description: "A blog for sharing thoughts on technology, architect about SaaS."
url: "http://murmur.tech"
ogimage: "img/default-ogimage.png"
author:
  name: "BoolFunc"
  email: "Pet-Pet@foxmail.com"
  url: "http://murmur.tech"


# Build settings
baseurl: /blog # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
